zarr-developers/VirtualiZarr

virtualizarr/manifests/array.py
virtualizarr/manifests/array_api.py
virtualizarr/tests/test_xarray.py

Closes part of #2.
To get this to work I had to add broadcasting, to cover times when xarray wants to insert a length-1 dimension. I did appreciate until now that actually we can go further and fully support broadcasting with `ManifestArray` objects!

Support xarray concat, including broadcasting

---

.github/workflows/main.yml
pyproject.toml
virtualizarr/kerchunk.py
virtualizarr/tests/test_kerchunk.py

Curious on what you think of this @TomNicholas. 
- Allows _automatically_determine_filetype to guess between netCDF3 vs netcdf4.
- Adds a `netCDF4` dependency to tests. 🤷

Adds netCDF3 vs netCDF4 distinction to _automatically_determine_filetype.

---

docs/api.md
virtualizarr/__init__.py
virtualizarr/kerchunk.py
virtualizarr/xarray.py

If we implement the suggestion in https://github.com/TomNicholas/VirtualiZarr/pull/45#issuecomment-2018420283, then we will have ways of creating datasets backed by ManifestArrays from disk that don't involve calling kerchunk. Therefore we should rename this function.

Rename open_dataset_via_kerchunk to open_virtual_dataset

---

virtualizarr/kerchunk.py

The NetCDF3 reader previously imported `SingleHDF5ToZarr`, instead of `NetCDF3ToZarr`.

Updated NetCDF IO path

---

docs/usage.md
virtualizarr/tests/test_xarray.py
virtualizarr/xarray.py

Towards implementing case (1) of #62, at least the opening step. We would still need to be able to save these loaded variables out (to kerchunk and zarr ideally). 
~~Mostly works but there is a subtlety with the difference between a `Variable` and an `IndexVariable` causing the test to fail.~~

Load selected variables instead of making them virtual

---

.github/workflows/main.yml

We had to pin kerchunk=0.2.2 because of this bug (https://github.com/fsspec/kerchunk/issues/445), but apparently that version of kerchunk cannot work in an environment with python 3.12 (see [this CI run](https://github.com/TomNicholas/VirtualiZarr/actions/runs/8578684155/job/23512827135) for example).

Remove python 3.12 from CI matrix

---

virtualizarr/manifests/array_api.py
virtualizarr/manifests/manifest.py
virtualizarr/tests/__init__.py
virtualizarr/tests/test_manifests/test_array.py

Fixes the other part of #100, specifically that when broadcasting a scalar array (i.e. a `ManifestArray` with `shape=()`), you need to not insert a new dimension into the chunk keys, because the chunk key is already `0` (not an empty string).

Fix bug with expand dims of a scalar array

---

docs/usage.md
pyproject.toml

Noticed while setting up my env. Now that [#8872](https://github.com/pydata/xarray/pull/8872) has merged

Install xarray from main 

---

.github/workflows/main.yml
pyproject.toml

Closes https://github.com/TomNicholas/VirtualiZarr/issues/77
Given that https://github.com/fsspec/kerchunk/issues/445 seems to be resolved on main. This PR unpins the kerchunk version and uses ~the unreleased version~ newly released 0.2.5 instead. ~To me it seems fair that this library would sometimes require unreleased kerchunk and that feels preferable to pinning down to an old release.~

Unpin kerchunk (set floor) and enable Python 3.12

---

docs/installation.md
pyproject.toml

Xarray [v2024.5.0](https://github.com/pydata/xarray/releases/tag/v2024.05.0) has the PR we need for concatenation without indexes (https://github.com/pydata/xarray/pull/8872) so we can depend on a proper released version of xarray from now on.

Depend on latest version of xarray

---

docs/usage.md
pyproject.toml
virtualizarr/tests/test_integration.py
virtualizarr/tests/test_kerchunk.py
virtualizarr/xarray.py

Closes #72 
I'm pretty sure this is not what you had in mind, but wanted to put this up as at least an option. Even if we scrap the implementation, the test should stay the same.
I didn't include remote writing since it seemed like that would be something that we'd want to implement for all the file outputs not just for one.

Write to parquet

---

pyproject.toml
virtualizarr/tests/conftest.py

Netcdf4 fix

---

pyproject.toml

Fix for an error that arises when using python3.9:
```
Python 3.9.19 (main, Mar 19 2024, 16:08:27) 
[Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from virtualizarr import open_virtual_dataset
Traceback (most recent call last):
...
File "/github/developmentseed/VirtualiZarr/virtualizarr/manifests/manifest.py", line 36, in ChunkEntry
def from_kerchunk(cls, path_and_byte_range_info: list[str | int]) -> "ChunkEntry":
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
as I believe the type union operator was only implemented in 3.10: https://docs.python.org/3/whatsnew/3.10.html#pep-604-new-type-union-operator

requires-python = ">=3.10"

---

virtualizarr/tests/test_xarray.py
virtualizarr/xarray.py

I noticed that reader_options were not being passed through to `read_kerchunk_references_from_file` in `open_virtual_dataset` when I was trying out the library with some files on S3 (e.g. `open_virtual_dataset(s3_link, reader_options={'storage_options': aws_creds})` would get a Forbidden error, see https://gist.github.com/abarciauskas-bgse/629702733946b1ec0b008f659dbc3406 for reproducible example).
This PR just adds one line so those args are passed through. I added a test but not sure if that is overkill for such a small change.

Pass args and add test

---

virtualizarr/tests/test_utils.py
virtualizarr/utils.py
virtualizarr/xarray.py

This change simplifies the handling of filepaths in `_fsspec_openfile_from_filepath`, and removes some restrictions around what can be passed in. Most notably, it allows the use of non-S3 and local filepaths.
I see that `virtualizarr/tests/test_xarray.py::test_anon_read_s3` covers this, but that's failing for me on `main` with
```pytb
E           aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host carbonplan-share.s3.regionone.amazonaws.com:443 ssl:default [Name or service not known]
```
Is that just a local configuration issue for me, or is it failing for others as well?

Allow other fsspec protocols than local and s3

---

pyproject.toml
virtualizarr/__init__.py

This PR makes the following work:
```
python -c "import virtualizarr; print(virtualizarr.__version__)"
```
Welcome any feedback, in particular if there's a reason to use setuptools_scm's `write_to` rather than `importlib.metadata`.

Add dunder version to top-level __init__.py

---

.github/workflows/release.yml
.gitignore
docs/contributing.md
docs/index.md
pyproject.toml
virtualizarr/__init__.py

This PR adds a GitHub workflow to test distributions using TestPyPI and upload releases to PyPI. (Same as #134 but not off a fork to allow testing the workflow)

Add release workflow

---

virtualizarr/tests/test_kerchunk.py
virtualizarr/tests/test_manifests/test_array.py
virtualizarr/tests/test_zarr.py
virtualizarr/zarr.py

See https://numpy.org/devdocs/numpy_2_0_migration_guide.html#main-namespace

Replace np.NaN with np.nan in preparation for numpy 2.0

---

pyproject.toml
virtualizarr/tests/__init__.py
virtualizarr/tests/test_manifests/test_array.py

This definitely found a few bugs, but I'm not sure there's any point fixing them in `main` when I'm about to change the entire implementation in #107 anyway...

Hypothesis test broadcasting

---

.github/workflows/release.yml
pyproject.toml

Including `local_scheme = "guess-next-dev"` in pyproject.toml caused the +unknown to be included in the distribution name. This PR removes that configuration and updates the release workflow to build the package on PRs, but only upload to TestPyPI for releases.
Relates to #13

Use default version scheme for setuptools_scm

---

docs/api.rst
docs/releases.rst
docs/usage.md
virtualizarr/manifests/array.py
virtualizarr/manifests/manifest.py
virtualizarr/tests/test_manifests/test_manifest.py
virtualizarr/tests/test_xarray.py
virtualizarr/xarray.py

Rename paths in manifest

---

docs/releases.rst
virtualizarr/tests/test_xarray.py
virtualizarr/xarray.py

Ensure _ARRAY_DIMENSIONS get dropped from attrs

---

docs/releases.rst
virtualizarr/tests/test_integration.py
virtualizarr/tests/test_xarray.py
virtualizarr/xarray.py

Ensure attributes on coordinate variables are preserved during round-tripping

---

docs/releases.rst
virtualizarr/kerchunk.py
virtualizarr/tests/test_integration.py
virtualizarr/xarray.py

Identify non dimension coords

---

virtualizarr/tests/test_integration.py

This just tests that we can round-trip correctly when writing kerchunk-format references to an in-memory dict as well as to disk.

Also test exporting references to in-memory kerchunk reference dict

---

ci/environment.yml
docs/contributing.md
docs/releases.rst
pyproject.toml
virtualizarr/kerchunk.py
virtualizarr/tests/test_kerchunk.py
virtualizarr/tests/test_xarray.py
virtualizarr/xarray.py

Use magic bytes to identify file formats

---

docs/releases.rst
virtualizarr/kerchunk.py
virtualizarr/tests/test_integration.py
virtualizarr/tests/test_xarray.py
virtualizarr/utils.py
virtualizarr/xarray.py

This is what I have started working on for the cftime_variables. I am going to be on vacation for a week so I thought I should show what I've gotten up to in case there is some urgency around this, but it is pretty WIP 🥲

Decoding `cftime_variables`

---

docs/releases.rst
virtualizarr/tests/test_integration.py
virtualizarr/tests/test_xarray.py
virtualizarr/xarray.py

Currently passing `indexes=None` to `open_virtual_dataset` isn't properly supported. But this is also the default (to give behaviour most similar to `xr.open_dataset`). Whilst all the documentation examples use the recommended `indexes={}`, this PR actually adds a `UserWarning` telling you to use `indexes={}`.

Warn on index creation

---

docs/releases.rst
docs/usage.md

Add example of using cftime_variables to usage docs

---

virtualizarr/manifests/manifest.py

This PR has a relatively small surface area: it simply swaps out int32 for uint64 so that chunk manifests can handle the large byte offsets and chunk sizes that are sometimes encountered

Future-proof offset and size records in chunkmanifest

---

virtualizarr/kerchunk.py
virtualizarr/tests/test_kerchunk.py

This PR uses a set comprehension rather than a list comprehension in `find_var_names` to drop all duplicate var names that happen to show up in the kerchunk reference dict.

Use a set to avoid duplicate var names from kerchunk

---

docs/releases.rst
virtualizarr/manifests/manifest.py
virtualizarr/tests/test_manifests/test_manifest.py

This was discovered while experimenting with [GOES](https://planetarycomputer.microsoft.com/dataset/goes-cmi) data, kudos to @t-mcneely for discovering this. We think there's a small bug in the filter expression during `ChunkDict` creation. Ultimately this caused a problem when reading/writing kerchunk stores of the data.
Here's a neat image rendering the chunk grid we were working with, note how the corners are empty:

Exclude empty `paths` on `ChunkDict` creation

---

virtualizarr/manifests/manifest.py

I'm trying to open a Zarr v2. I couldn't find a good obvious way to do this, so my attempt was:
```python
from kerchunk.zarr import ZarrToZarr
from virtualizarr.xarray import dataset_from_kerchunk_refs
ref = ZarrToZarr(url).translate()
ds = dataset_from_kerchunk_refs(ref)
```
This fails [here in unpacking](https://github.com/zarr-developers/VirtualiZarr/blob/f60707f86f6fa7415463c1a3e886eb134b84bdb0/virtualizarr/manifests/manifest.py#L39) because kerchunk produces reference entries of the form `[path]` instead of `[path, length, offset]`.
I was wondering if I could work around this by `stat`ing the chunks, and sure enough it worked! (See my second commit.)
I'd love to get some feedback on this, including if there's a better way to open v2 zarrs.
In preparation for my second commit I needed …

Extend refspec support to [path] entries (without offset/length)

---

virtualizarr/tests/test_xarray.py
virtualizarr/xarray.py

https access fix

---

conftest.py
docs/releases.rst
pyproject.toml
virtualizarr/tests/test_xarray.py
virtualizarr/xarray.py

Some real-world NetCDF files have scalar variables that `kerchunk` parsers to a ChunkDict of `{}`. Previously, these variables would need to be explicitly loaded or dropped to make a `open_virtual_dataset` call work. With this change, the variable will be loaded into `xr.Variables` of dimension 0 and their attributes passed up to the XArray dataset.

Handle scalar dataset variables

---

.pre-commit-config.yaml

In https://github.com/zarr-developers/VirtualiZarr/issues/180, it seems like the Github pre-commit CI wasn't working on PR's. I enabled the app in the repo (08-05-2024). This is a tiny PR that bumps a ruff version & updates the .pre-commit-config.yaml mypy section to replace `types-pkg_resources` with `types-setuptools`.

Update .pre-commit-config mypy + bump ruff version 

---

.github/workflows/main.yml
.pre-commit-config.yaml
ci/environment.yml
pyproject.toml
virtualizarr/kerchunk.py
virtualizarr/manifests/array.py
virtualizarr/manifests/manifest.py
virtualizarr/tests/test_zarr.py
virtualizarr/xarray.py
virtualizarr/zarr.py

This updates how we do static type checking, and fixes some issues on `main`.
The biggest change is moving the `mypy` linting check out of `.pre-commit`. As mentioned in https://github.com/zarr-developers/VirtualiZarr/issues/209, we need *all* the typed dependencies in the environment running the check. The one managed by .pre-commit was lacking several dependencies (like xarray and Zarr) and so we weren't benefiting from static type checking at those boundaries. We can move it back into pre-commit, but we need to make sure that all our dependencies are duplicated there.
I'll explain some of the type changes inline.

Update static typing

---

.github/workflows/main.yml

Adds concurrency field to main.yml in Github CI. Ensures in-progress jobs are canceled on re-runs. Completes one of the [repo-review results](https://github.com/zarr-developers/VirtualiZarr/issues/99) - `├── GH102 Auto-cancel on repeated PRs ❌`

Adds concurrency to CI w/ cancel-in-progress=True

---

ci/environment.yml
docs/releases.rst
pyproject.toml
virtualizarr/manifests/manifest.py
virtualizarr/tests/test_kerchunk.py
virtualizarr/tests/test_manifests/test_manifest.py
virtualizarr/tests/test_zarr.py
virtualizarr/zarr.py

This removes our pydantic dependency by reimplementing them with dataclasses. There are a few breaking changes:
1. The classes won't automatically cast the argumetns to the declared type. IMO, that's the preferable behavior. Some backwards compatability shims have been added for np.dtype, but perhpas we want to remove that too.
2. The models won't have any of the methods they previously inherited from pydantic.BaseModel. This is probably good for user-facing objects, we now have full control over the public API.
3. We had to reorder some of the fields on ZArray, since dataclasses is stricter about positional arguments. I've aligned the order with `zarr.create`.
The tests did need to be updated in a few places (we compare some strings, and the order changed, and we don't automatically cast …

Implement pydantic models as dataclasses

---

docs/conf.py

This is option 1 from https://github.com/zarr-developers/VirtualiZarr/issues/220#issuecomment-2284548652: keep using `pydata_sphinx_theme`, but use the proper html theme options.
Edit: looks like the `html_context` options (`github_user`, `github_repo`, `github_version`, `docs`) are there to add a source edit link, which has to be enabled with `use_edit_page_button`.
For the link to github, we needed to add an [icon link](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/header-links.html#icon-links).

use the theme options for `pydata_sphinx_theme`

---

docs/releases.rst
virtualizarr/readers/zarr.py

Tiny PR that adds `None` as defaults to `drop_variables` and `indexes` in `open_virtual_dataset_from_v3_store`. These defaults mirror `open_virtual_dataset`. 
Might add a bit of QOL for behavior like: `TypeError: open_virtual_dataset_from_v3_store() missing 1 required positional argument: 'drop_variables'
`

Adds defaults in `open_virtual_dataset_from_v3_store`

---

docs/releases.rst
examples/coiled/terraclimate.ipynb

Inspired by @thodson-usgs's [Lithops example](https://github.com/zarr-developers/VirtualiZarr/pull/203), I've created a Virtualizarr example using [coiled](https://www.coiled.io/) [serverless](https://docs.coiled.io/user_guide/functions.html#api) functions.  
- 1TB virtual dataset from 924 NetCDF files
- 9 minutes and ~$0.24 of cloud cost on coiled
Would love some feedback if anyone has thoughts.

Virtualizarr + Coiled Serverless Example Notebook

---

virtualizarr/backend.py

Tiny typo in warning. 
(functionally perfect as I just experienced following the warning's advice)

Update backend.py (tiny typo)

---

.github/workflows/main.yml
.github/workflows/typing.yml

Type checking is failing, but it's the [same three](https://github.com/zarr-developers/VirtualiZarr/issues/249).
- Should we keep the python version matrix for mypy? 
- Installing all of the deps listed in `test` seems pretty overkill just for some typing library stubs. Is there a better alternative?

Makes mypy a seperate CI job

---

virtualizarr/manifests/array_api.py
virtualizarr/manifests/manifest.py

Hoping this fixes some of the typing errors @norlandrhagen flagged in #249

Fix mypy errors around numpy functions not being strictly type hinted

---

.github/workflows/main.yml
.gitignore
ci/doc.yml
conftest.py
docs/releases.rst
docs/usage.md
pyproject.toml
virtualizarr/backend.py
virtualizarr/manifests/manifest.py
virtualizarr/readers/kerchunk.py
virtualizarr/tests/test_backend.py
virtualizarr/tests/test_utils.py
virtualizarr/utils.py

To Do:
Notes:
- Mypy checks in CI are currently disabled! https://github.com/zarr-developers/VirtualiZarr/issues/249
- The utility function `_fsspec_openfile_from_filepath` forced the fsspec filesystem to open a filepath (the fault of past me). I replaced it with a simple class that has a `.open_file` method that can be used as needed. The Kerchunk `LazyReferenceMapper` required a fsspec filesystem.

Allow `open_virtual_dataset` to read existing Kerchunk references

---

virtualizarr/backend.py
virtualizarr/readers/common.py
virtualizarr/readers/dmrpp.py
virtualizarr/readers/fits.py
virtualizarr/readers/hdf5.py
virtualizarr/readers/kerchunk.py
virtualizarr/readers/netcdf3.py
virtualizarr/readers/tiff.py
virtualizarr/readers/zarr_v3.py

For some reason I always thought that `Variable` and `Index` were private xarray internals, but they are actually available in the top-level namespace!
Now the only things we import from xarray that aren't at the top level are
```python
from xarray.backends import AbstractDataStore, BackendArray
from xarray.core.indexes import PandasIndex
```
which are both semi-public anyway.

Import top-level version of xarray classes

---

virtualizarr/readers/common.py

This was originally just an idea towards implementing #35, but it's not currently being used, so I'm removing it. It also appears to be causing a [typing error](https://github.com/zarr-developers/VirtualiZarr/actions/runs/11602730981/job/32308312980?pr=191) in https://github.com/zarr-developers/VirtualiZarr/pull/191.

Remove unused ManifestBackendArray class

---

ci/environment.yml
ci/min-deps.yml
ci/upstream.yml
docs/releases.rst
pyproject.toml
virtualizarr/readers/common.py

This bumps the minimum required version of xarray to the most recent release, which includes support for zarr-python v3 and for `xr.DataTree`. This shouldn't break compatibility with anything.

Bump minimum Xarray dependency to 2024.10.0

---

docs/releases.rst

I should have added a new section to the release notes when I released v1.1.0.

Fix release notes for v1.1.0

---

ci/upstream.yml

support for zarr v3 numcodecs codecs has been released in numcodecs 0.14.0. This PR just updates the upstream ci to match
As noted in https://github.com/earth-mover/icechunk/issues/197

Remove numcodecs specific install

---

.readthedocs.yml
docs/conf.py
virtualizarr/manifests/manifest.py

This PR auto generates section references and updates the readthedocs CI to not fail on warnings
Closes #299

Fix sphinx warnings

---

docs/contributing.md
docs/releases.rst

Changed the command to install the project for docs development to use `python -m pip`. This ensures that the Python interpreter from the activated environment is used when installing the package in editable mode.

Update pkg install in docs contribution guide

---

docs/releases.rst

Following https://peps.python.org/pep-0561/, a package must add a marker file named `py.typed` to their package to suppoer type checking of their code. I'd like to use VirtualiZarr's type checking in https://github.com/developmentseed/virtualize-nex-gddp-cmip6 and expect others would find this helpful, so this PR adds the marker file to the package.

Support downstream type checking by including py.typed

---

virtualizarr/tests/test_readers/test_kerchunk.py

@norlandrhagen this refactors the tests in `test_readers/test_kerchunk.py` to all call `open_virtual_dataset` directly instead of calling the internal function `dataset_from_kerchunk_refs`. This will help me test that passing `fs_root` to `open_virtual_dataset` is working as expected.

Refactor kerchunk reader tests to call open_virtual_dataset

---

virtualizarr/tests/test_readers/test_dmrpp.py

Refactor dmrpp tests to expose data file path

---

docs/releases.rst
docs/usage.md

These links still don't actually create hyperlinks, but at least this fixes one type of bug with them (that they pointed to modules which have since been renamed).

Correct some documentation links to function the public API

---

virtualizarr/readers/hdf/hdf.py

Closes spontaneous mypy errors for h5py classes but we should leave #324 open for further investigation into root causes.

Ignore spontaneous mypy errors for h5py classes. ref #324

---

docs/contributing.md

I split up the steps in https://github.com/zarr-developers/VirtualiZarr/pull/332 and https://github.com/zarr-developers/VirtualiZarr/commit/7fbc2bc62cca478e6ac995168902a5a633845a73, which seems to have fixed the problem, thanks @maxrjones ! 
This PR updates the release guide so I don't make that mistake again.

Release guide release notes correction

---

conftest.py
docs/contributing.md
docs/releases.rst
virtualizarr/readers/fits.py
virtualizarr/readers/hdf5.py
virtualizarr/readers/netcdf3.py
virtualizarr/readers/tiff.py
virtualizarr/tests/test_backend.py
virtualizarr/tests/test_integration.py
virtualizarr/translators/kerchunk.py

This also changes the expected behaviour of `open_virtual_dataset(file, group=None)` (i.e. the default value of the `group` kwarg) when multiple groups are encountered. It now just opens the root group instead of raising, which is more consistent with `xr.open_dataset`.

Fix group kwarg

---

docs/api.rst
docs/releases.rst
docs/usage.md
virtualizarr/readers/common.py
virtualizarr/tests/test_backend.py
virtualizarr/tests/test_xarray.py

I think the warning being thrown here was really a misguided attempt to ensure that variables in the virtual dataset aren't too large. But generally it's much simpler to just create indexes for loadable variables instead, and not throw a warning.

Remove warning when passing  indexes=None

---

.github/codecov.yml
.github/workflows/main.yml

Based on Zarr-Python, I think it should work to put the configuration inside .github rather than the repository root, but let's see...

Configure codecov to ignore tests folder

---

docs/releases.rst
virtualizarr/readers/fits.py
virtualizarr/tests/__init__.py
virtualizarr/tests/test_backend.py
virtualizarr/tests/test_readers/test_dmrpp.py
virtualizarr/tests/test_readers/test_fits.py

Small bugfix for the FITS reader, tested by trying to read one of the FITS files stored in AWS comprising the Hubble Space Telescope data archive.
Also renames the `@network` test decorator to `@requires_network`.

Test FITS reader on Hubble Space Telescope data

---

docs/releases.rst
virtualizarr/readers/hdf/hdf.py
virtualizarr/tests/test_readers/test_hdf/test_hdf.py

Fixes #364 by removing the subgroup prefix from the returned dimension names.

Fix subgroup dims in HDF reader

---

.pre-commit-config.yaml
docs/releases.rst
pyproject.toml
virtualizarr/tests/test_readers/conftest.py
virtualizarr/tests/test_writers/test_icechunk.py
virtualizarr/writers/icechunk.py

Apologies for a bit of extra diff in `test_icechunk.py`, most of which comes from adding `xr` and `zarr` namespace prefixes in a number of places, as it was rather confusing to determine which functions and classes were coming from where.

Add `group` option to `dataset_to_icechunk`

---

.github/workflows/main.yml
.github/workflows/min-deps.yml
.github/workflows/release.yml
.github/workflows/typing.yml
.github/workflows/upstream.yml

In addition, to aid in use of [`act`](https://github.com/nektos/act) for locally running GH jobs:
- Uniquely name test jobs
- Use `micromamba` in place of `conda` because, oddly, `act` containers are unable to find `conda`, and fail

Silence pip root user warnings in CI

---

ci/upstream.yml
conftest.py
pyproject.toml
virtualizarr/tests/test_writers/test_icechunk.py
virtualizarr/writers/icechunk.py

This is a bit of follow-on work from #383, addressing a plethora of warnings emitted during execution of icechunk tests (upstream test job): primarily deallocating cachefilemanager warnings (due to unclosed file handles), but also warnings for skipping of async test functions, and unknown "flaky" marker.
There's also a bit of additional test coverage and docstring details for `dataset_to_icechunk` that I was too slow to push before #383 was merged.

Address warnings emitted during test execution for deallocating cachefilemanager 

---

.coveragerc
.github/codecov.yml
.github/workflows/main.yml
.github/workflows/min-deps.yml
.github/workflows/upstream.yml
ci/environment.yml
ci/min-deps.yml
ci/upstream.yml
docs/contributing.md
pyproject.toml

In addition, make it easier for produce coverage report locally by adding pytest config options to pyproject.toml. This also produces consistent results between local runs and runs in CI, and adds a term-missing report for human readability, both for local runs as well as in CI, so it show up in the logs.

Ignore conftest.py in code coverage

---

docs/usage.md

Adds a new scenario to the list of scenarios for usage of `load_variables` in the "Loading variables" subsection of the "Usage" doc page. Also, adds a subsubsection to "Loading variables" detailing how one may want to load all low dimensional coordinates.

Updated docs for loading variables

---

docs/releases.rst
virtualizarr/readers/netcdf3.py
virtualizarr/tests/test_readers/conftest.py
virtualizarr/tests/test_readers/test_netcdf3.py
virtualizarr/vendor/kerchunk/LICENSE.txt
virtualizarr/vendor/kerchunk/netCDF3.py
virtualizarr/vendor/kerchunk/utils.py

Passes locally with zarr v2. But I think this will break for an env with zarr v3 in it.

Vendor kerchunk netCDF3 reader

---

docs/releases.rst
virtualizarr/backend.py
virtualizarr/readers/hdf/hdf.py
virtualizarr/tests/__init__.py
virtualizarr/tests/test_backend.py
virtualizarr/tests/test_integration.py
virtualizarr/tests/test_readers/test_hdf/test_hdf.py
virtualizarr/tests/test_xarray.py

* Switches autodetected backend selection
* updates tests to require kerchunk less often
* only test kerchunk hdf reader if kerchunk is available

Switch to custom netcdf4/hdf5 backend

---

docs/usage.md

Update usage.md with append method for icechunk

---

virtualizarr/readers/hdf/hdf.py
virtualizarr/tests/test_backend.py
virtualizarr/tests/test_readers/conftest.py
virtualizarr/tests/test_readers/test_hdf/test_hdf_integration.py
virtualizarr/tests/test_xarray.py

Fix HDFVirtualBackend handling of non coordinate dimension HDF datasets.

---

.github/workflows/main.yml
ci/environment.yml
docs/releases.rst
pyproject.toml

Long-awaited part of #392, as it allows us to pin `zarr-python>=3`!
cc @mpiannucci the warning in the icechunk docs can be updated now (though virtualizarr still needs to be fixed to work with the latest version of icechunk).

Update to zarr-v3-compatible released version of Kerchunk (0.2.8)

---

ci/environment.yml

Icechunk seems to be on conda now, so let's install it from conda instead of pip in the CI

Install Icechunk from Conda in CI

---

README.md

Minor changes to readme to connect virtualizarr to the concept of a "datacube".

Store -> Datacube language in readme

---

virtualizarr/readers/hdf/hdf.py
virtualizarr/tests/test_readers/conftest.py
virtualizarr/tests/test_readers/test_hdf/test_hdf.py
virtualizarr/tests/test_readers/test_hdf/test_hdf_integration.py

Reapply reverted changes from #420, but with tests modified to use context managers to cleanup resources in an attempt to  prevent the build from hanging during unit tests.

Reapply HDF reader fillvalue

---

ci/environment.yml
ci/upstream.yml
docs/releases.rst
pyproject.toml

Update minimum icechunk version to v0.2.4

---

ci/environment.yml

Prevent pytest skipping async tests and eliminate the following warnings issued during unit test execution:
- /root/micromamba/envs/virtualizarr-tests/lib/python3.11/site-packages/_pytest/config/__init__.py:1441: PytestConfigWarning: Unknown config option: asyncio_default_fixture_loop_scope
- .../VirtualiZarr/virtualizarr/tests/test_writers/test_icechunk.py:642: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
- /root/micromamba/envs/virtualizarr-tests/lib/python3.11/site-packages/_pytest/python.py:148: PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.

Add missing pytest-asyncio plugin

---

conftest.py
virtualizarr/backend.py
virtualizarr/tests/test_backend.py
virtualizarr/tests/test_integration.py
virtualizarr/tests/test_readers/conftest.py
virtualizarr/tests/test_readers/test_hdf/test_hdf_integration.py
virtualizarr/tests/test_xarray.py

Elimiinate 32 of 70 of the following warnings emitted while running unit tests: `RuntimeWarning: deallocating CachingFileManager`
The remaining 38 appear to all be related to the HDF5VirtualBackend, so they are not addressed in this PR, as they will require some code refactoring, as identified in #468.
Fixes #390

Use context managers in test functions

---

virtualizarr/writers/kerchunk.py

Xarray no longer casts datetimes during encoding, so we need to when inlining variables to Kerchunk.

Cast encoded datetimes

---

.github/workflows/main.yml
.github/workflows/typing.yml

I realized in debugging https://github.com/zarr-developers/VirtualiZarr/issues/492 that our current strategy for listing installed dependencies in the CI is not comprehensive. This updates the workflows to first install the environment with pixi and then use `pixi list` which gives us a complete list.

List all installed libraries in CI

---

docs/conf.py

@kylebarron made a great suggestion in https://github.com/zarr-developers/VirtualiZarr/pull/490#discussion_r2010683170 to use intersphinx references. This basically makes all the types in the function signatures clickable to get to the relevant documentation in NumPy, Zarr, Python, and Xarray, which is pretty great.

Setup intersphinx mapping for docs

---

pyproject.toml

This reduces the testing time for me from 44s to 31s. It doesn't impact the number of passing tests, but increases the number of warnings from 423 to 444. I think we can resolve those warnings separately.
Thanks goes to Anthony Lukach for pointing out this great pytest plugin..

Use pytest-xdist to distribute tests across CPUs

---

pyproject.toml
virtualizarr/readers/hdf/hdf.py

`from __future__ import annotations` allows type checking optional dependencies. Also simplified the pyproject.toml a bit.

Simplify hdf5 typing

---

.github/workflows/upstream.yml

The upstream build takes a while and IMO doesn't need to be run on every commit to PRs. This separates out the upstream tests so that they only get run on a commit to main/develop, on the nightly chron job, and when a PR is labeled with 'test-upstream'.

Run upstream tests nightly, commits to main/dev, and on labeled PRs

---

virtualizarr/readers/common.py

Eliminate 219 of the following warnings emitted during run of tests (via `pixi run -e test run-tests`):
```
RuntimeWarning: deallocating CachingFileManager(...), but file is not already closed. This may indicate a bug.
vds = replace_virtual_with_loadable_vars(
```

Fix resource leak from unclosed dataset

---

virtualizarr/manifests/store.py
virtualizarr/manifests/utils.py
virtualizarr/tests/test_manifests/test_store.py

This PR improves ManifestStore to support ManifestArrays that only contain a single entry in paths, offsets, and lengths. It was originally included in https://github.com/zarr-developers/VirtualiZarr/pull/516 but I've pulled these changes out because they are also needed for the TIFF reader.

Properly extract chunk keys for arrays with a single chunk

---

docs/faq.md
docs/releases.rst
virtualizarr/common.py
virtualizarr/manifests/group.py
virtualizarr/manifests/store.py
virtualizarr/readers/fits.py
virtualizarr/readers/hdf/hdf.py
virtualizarr/readers/hdf5.py
virtualizarr/readers/netcdf3.py
virtualizarr/readers/tiff.py
virtualizarr/tests/test_manifests/test_store.py
virtualizarr/tests/test_writers/test_icechunk.py
virtualizarr/translators/kerchunk.py
virtualizarr/xarray.py

Adds `loadable_variables` kwarg to `ManifestStore.to_virtual_dataset()` method, which will makes reader implementations simpler. 
Also refactors `common.py` (to now be called `xarray.py`), such that we can use the same `construct_virtual_dataset` function from it in every reader, regardless of whether or not that reader yet uses `ManifestStore`.
cc @sharkinsspatial

Add loadable_variables kwarg to ManifestStore.to_virtual_dataset()

---

.pre-commit-config.yaml
pyproject.toml
virtualizarr/manifests/__init__.py
virtualizarr/manifests/store.py
virtualizarr/readers/hdf/hdf.py
virtualizarr/tests/conftest.py
virtualizarr/tests/test_integration.py
virtualizarr/tests/test_manifests/test_store.py
virtualizarr/tests/test_readers/conftest.py
virtualizarr/tests/test_readers/test_hdf/test_hdf_manifest_store.py
virtualizarr/utils.py

This PR makes it possible to have an empty dict in `ManifestStores._stores` and automatically create an S3Store or LocalStore from a filepath.
Part of https://github.com/zarr-developers/VirtualiZarr/issues/498

Add ObjectStoreRegistry to support default stores

---

.gitignore
.pre-commit-config.yaml
docs/data_structures.md
docs/faq.md
docs/index.md
docs/installation.md
docs/releases.rst
docs/usage.md
examples/coiled/terraclimate.ipynb
examples/mursst-icechunk-with-lithops/README.md
examples/mursst-icechunk-with-lithops/ec2_for_lithops_runtime/README.md
virtualizarr/manifests/array_api.py
virtualizarr/manifests/manifest.py
virtualizarr/readers/dmrpp.py
virtualizarr/readers/kerchunk.py
virtualizarr/tests/test_writers/test_icechunk.py

This PR moves the understanding oriented documentation to a separate data structures page to keep the usage guide focused on practical activities, following the [Diátaxis framework](https://diataxis.fr/).

Separate understanding (data models) from learning (usage) in docs

---

virtualizarr/manifests/array.py
virtualizarr/tests/test_manifests/test_array.py

Improves error reporting in unsupported indexing cases, which can happen when trying to do complex xarray concatenations.

Improve indexing errors

---

docs/faq.md

I had a (reasonable) complaint that this was not clear enough.

Make the supported and non-supported filetypes clearer in the FAQ

---

docs/custom_readers.md
docs/data_structures.md
docs/faq.md
docs/index.md
docs/releases.rst
docs/usage.md

A lot of small adjustments, and then a brand new page of docs.

Docs on how to write a custom reader using ManifestStore

---

virtualizarr/tests/test_manifests/test_store.py
virtualizarr/tests/test_readers/test_hdf/test_hdf_manifest_store.py

The test suite was failing on a local machine without an internet connection - this fixes it.

Add requires_network decorator to tests that were missing it

---

pyproject.toml

Fixing dependency resolution, See https://github.com/fsspec/s3fs/pull/966 for context

Fix upstream tests by removing fsspec pin

---

.github/workflows/upstream.yml
pyproject.toml

This seems important since we use parts of Xarray and Zarr's private APIs.

Test against minimum supported version of dependencies

---

virtualizarr/tests/test_integration.py
virtualizarr/tests/test_writers/test_icechunk.py

Use read-only stores with `xr.open_zarr()`.

Fix icechunk tests with Zarr 3.0.9

---

virtualizarr/manifests/store.py

Pickling support was added upstream in https://github.com/developmentseed/obstore/releases/tag/py-v0.4.0 so we do not need this code.

Remove unnecessary custom pickling support

---

pyproject.toml
virtualizarr/tests/test_integration.py
virtualizarr/tests/test_writers/test_icechunk.py

Following https://icechunk.io/en/latest/migration/#virtual-datasets

Migrate to Icechunk v1.0, exclude broken Xarray compatibility

---

conftest.py
virtualizarr/manifests/array_api.py
virtualizarr/tests/test_manifests/test_array.py

This splits out part of #677, by adding some targeted unit tests for a part of the array_api that probably should have been added when I first wrote that module.

Add some units tests for `result_dtype`

---

conftest.py
virtualizarr/manifests/store.py
virtualizarr/tests/test_manifests/test_array.py
virtualizarr/tests/test_manifests/test_store.py
virtualizarr/tests/test_parsers/test_dmrpp.py
virtualizarr/tests/utils.py

Zarr python allows some exceptions to pass because nodes in the hierarchy that contain only fill values can be represented by missing files. We have a different way of representing missing files after https://github.com/zarr-developers/VirtualiZarr/pull/668, so we should never be expecting to have a failed get request due to a FileNotFoundError. I don't think we should expect the other errors used in regular Zarr store implementations.
TODO:

Do not allow exceptions in ManifestStore

---

pyproject.toml

We currently only support one version of xarray, see https://github.com/zarr-developers/VirtualiZarr/actions/runs/16381686949/job/46294326109?pr=703 for incompatibility with earlier versions and https://github.com/zarr-developers/VirtualiZarr/issues/688 for compatibility with future versions

Pin xarray to 2025.06.0

---

conftest.py
virtualizarr/parsers/dmrpp.py
virtualizarr/parsers/fits.py
virtualizarr/parsers/hdf/hdf.py
virtualizarr/parsers/kerchunk/json.py
virtualizarr/parsers/kerchunk/parquet.py
virtualizarr/parsers/netcdf3.py
virtualizarr/parsers/tiff.py
virtualizarr/parsers/typing.py
virtualizarr/parsers/zarr.py
virtualizarr/tests/test_integration.py
virtualizarr/tests/test_parsers/test_dmrpp.py
virtualizarr/tests/test_parsers/test_fits.py
virtualizarr/tests/test_parsers/test_hdf/test_hdf.py
virtualizarr/tests/test_parsers/test_hdf/test_hdf_integration.py
virtualizarr/tests/test_parsers/test_hdf/test_hdf_manifest_store.py
virtualizarr/tests/test_parsers/test_kerchunk.py
virtualizarr/tests/test_parsers/test_netcdf3.py
virtualizarr/tests/test_parsers/test_zarr.py
virtualizarr/tests/test_writers/test_icechunk.py
virtualizarr/tests/test_xarray.py
virtualizarr/tests/utils.py
virtualizarr/xarray.py

This is a breaking change to have consistent parameter names across the library for V2.

Standardize open_virtual_*dataset/parser signature to use "url"

---

virtualizarr/parsers/kerchunk/json.py

This is not used or needed, so removing it from the parser configuration.

Remove unused store_registry argument from KerchunkJSONParser.__init__

---

docs/custom_parsers.md
virtualizarr/manifests/store.py
virtualizarr/parsers/dmrpp.py
virtualizarr/parsers/fits.py
virtualizarr/parsers/hdf/hdf.py
virtualizarr/parsers/kerchunk/json.py
virtualizarr/parsers/kerchunk/parquet.py
virtualizarr/parsers/netcdf3.py
virtualizarr/parsers/tiff.py
virtualizarr/parsers/zarr.py
virtualizarr/tests/test_manifests/test_store.py
virtualizarr/tests/test_parsers/test_kerchunk.py

Some API signatures used `store_registry` to accept ObjectStoreRegistry instances, and some used `registry. This PR standardized on `registry` throughout the API.

Consistently use 'registry' rather than a mix with 'store_registry'

---

conftest.py
docs/index.md
pyproject.toml
virtualizarr/codecs.py
virtualizarr/parsers/hdf/hdf.py
virtualizarr/parsers/kerchunk/translator.py
virtualizarr/tests/__init__.py
virtualizarr/tests/test_integration.py
virtualizarr/tests/test_parsers/test_dmrpp.py
virtualizarr/tests/test_writers/test_kerchunk.py
virtualizarr/tests/test_xarray.py
virtualizarr/utils.py

This PR applies @d-v-b's suggestion from https://github.com/zarr-developers/numcodecs/issues/767#issuecomment-3094441284 to use the filters argument in ArrayV2Metadata to store all codecs, to avoid a regression where we truncate the number of BytesBytesCodecs.

Include all V2 codecs as filters

---

virtualizarr/utils.py

The filters argument should be either a populated list or `None`, not an empty list.

Do not pass an empty filters list to ArrayV2Metadata

---

docs/releases.md
virtualizarr/tests/test_writers/test_icechunk.py
virtualizarr/writers/icechunk.py

This should fix the problem exposed in #740

Don't write empty chunks to icechunk

---

docs/migration_guide.md

I am refactoring some of my code to virtualize NASA data to v2 at the moment, and just spent a bunch of minutes debugging a permission denied error due to me just copy/pasting the code in the example. 
Wondering if it would be instructive for users to know that this option is specific to the data used.

Add comment on skip_signature=True in the s3 store example

---

docs/migration_guide.md
docs/usage.md

Wondering your thoughts on this @TomNicholas and @maxrjones. Do we want to show tabs for multiple store configs and should they be on the usage page or somewhere else in the docs?

Adds Mkdocs alternatate tabs to show multiple store configurations on Usage.md

---

docs/usage.md
virtualizarr/manifests/store.py

Obstore expects the preceding '/' to be stripped.

Always strip preceding / from path in ManifestStore

---

docs/releases.md
virtualizarr/manifests/store.py
virtualizarr/tests/test_writers/test_icechunk.py
virtualizarr/writers/icechunk.py

I think we need much more work around our handling of codecs (which would get much easier with https://github.com/zarr-developers/zarr-python/pull/3276), but this is a more immediate fix to support parsers that specify any serializer other than the default (e.g., big-endian bytes).
This makes your NetCDF3 example work @rsignell

Include serializer from ManifestStore in Icechunk virtual references

---

docs/releases.md
virtualizarr/tests/test_writers/test_kerchunk.py
virtualizarr/utils.py

This PR complements #766 by adding to_kerchunk support (whereas #766 added to_icechunk support). For a more robust long-term solution that would eliminate the need for separate metadata pipelines between kerchunk and icechunk, see issue #768.
@rsignell I tested your workflow works using this PR (see https://github.com/maxrjones/test-scripts/blob/main/test-virtualizarr-netcdf3/test-virtualizarr.py).

Extract endianness from Bytes codec in V2 metadata conversion

---

docs/releases.md
virtualizarr/tests/test_writers/test_icechunk.py
virtualizarr/writers/icechunk.py

Currently, serializing a `ManifestArray` containing empty chunks to Icechunk requires explicitly passing `validate_containers=False` to `to_icechunk` which may be counterintuitive for some users.  ref https://github.com/zarr-developers/VirtualiZarr/issues/740.  This PR changes the current behavior to only perform reference validation for references with a `path`.

Do not validate references for "empty" chunks.

---

docs/releases.md
pyproject.toml

It'd be nice to release today to unblock the earthaccess team

Polish release notes for v2.1.2

---

docs/examples.md

Looks like #644 broke the examples' links in the documentation. This PR fixes them.
Maybe we should move the examples into the docs folder so the documentation can use local paths?

Fix examples' links
