- docs/usage.md
> More narrative docs

- virtualizarr/kerchunk.py
- virtualizarr/tests/test_kerchunk.py
Minor PR to catch case where user defined filetype is not a `FileType`
> Convert user defined filetype to FileType

- .github/workflows/main.yml
- .pre-commit-config.yaml
- ci/doc.yml
- pyproject.toml
- virtualizarr/kerchunk.py
- virtualizarr/manifests/array.py
- virtualizarr/manifests/array_api.py
- virtualizarr/manifests/manifest.py
- virtualizarr/tests/test_kerchunk.py
- virtualizarr/tests/test_xarray.py
- virtualizarr/xarray.py
- virtualizarr/zarr.py
I updated and ran pyupgrade in a separate commit.
Closes #111 
EDIT: Feel free to ignore this if it's not a good time because of outstanding PRs.
> Remove python 3.9

- .github/PULL_REQUEST_TEMPLATE.md
- docs/index.md
- docs/releases.rst
> Release notes page

- .github/workflows/release.yml
Do not run test workflow on PRs to avoid naming conflicts on TestPyPI when using 'no-local-version' (e.g., https://github.com/zarr-developers/VirtualiZarr/actions/runs/9490667436/job/26154585576?pr=138)
> Only run distribution workflow on releases

- virtualizarr/kerchunk.py
- virtualizarr/utils.py
> change default reader_options to None

- docs/releases.rst
> Empty release notes for v0.2

- .github/workflows/main.yml
- ci/environment.yml
> Install dependencies for tests via mamba

- README.md
- docs/faq.md
- docs/index.md
- docs/releases.rst
> Update roadmap for v1.0

- virtualizarr/manifests/array.py
- virtualizarr/manifests/array_api.py
> xr.testing with ManifestArray fix (update isnan ufunc)

- virtualizarr/kerchunk.py
- virtualizarr/tests/test_xarray.py
- virtualizarr/utils.py
- virtualizarr/xarray.py
Removes the s3 remote_option defaults. Hopefully address https://github.com/zarr-developers/VirtualiZarr/issues/222
> Removes default storage options

- docs/contributing.md
- docs/releases.rst
Improves the contributing guide by making some small clarifications, fixes, and filling in some omissions.
FYI @maxrjones
> Update contributors guide

- README.md
- docs/faq.md
- docs/index.md
- docs/usage.md
Friendlier language towards pre-cloud file formats
> Legacy->archival

- ci/upstream.yml
- docs/releases.rst
- docs/usage.md
- pyproject.toml
- virtualizarr/accessor.py
- virtualizarr/tests/test_writers/test_icechunk.py
- virtualizarr/writers/icechunk.py
> Sync with icechunk alpha 8

- virtualizarr/readers/hdf/hdf.py
Works locally, hopefully this works in the CI too...
> Fix hdf typing

- ci/environment.yml
- ci/upstream.yml
- docs/releases.rst
- pyproject.toml
> Update Icechunk dependency to v0.1.1

- ci/environment.yml
- ci/upstream.yml
- pyproject.toml
- virtualizarr/writers/icechunk.py
> Upgrade icechunk 0.2.0

- ci/environment.yml
- docs/releases.rst
- virtualizarr/tests/test_writers/test_icechunk.py
- virtualizarr/writers/icechunk.py
> Update `store.set_virtual_ref` -> `store.set_virtual_refs`

- virtualizarr/readers/hdf/hdf.py
> Raise an ImportError for HDFVirtualBackend without h5py installed.

- docs/usage.md
Credit to @RobertPincus for catching these.
> Typo in usage docs

- README.md
just noticed the cworthy link was busted, this fixes it.
> fix [c]worthy link

- docs/usage.md
- virtualizarr/manifests/array_api.py
- virtualizarr/tests/test_integration.py
- virtualizarr/tests/test_readers/test_kerchunk.py
- virtualizarr/tests/test_xarray.py
Fixes links from before the repo transfer and remove notes for items no longer planned.
> Fix broken and outdated references

- virtualizarr/backend.py
- virtualizarr/manifests/array.py
- virtualizarr/tests/test_manifests/test_array.py
- virtualizarr/translators/kerchunk.py
> Remove `virtual_array_class_kwarg`

- conftest.py
- docs/conf.py
- docs/releases.rst
- docs/usage.md
- pyproject.toml
- virtualizarr/backend.py
- virtualizarr/manifests/array.py
- virtualizarr/manifests/utils.py
- virtualizarr/parallel.py
- virtualizarr/readers/api.py
- virtualizarr/readers/common.py
- virtualizarr/readers/dmrpp.py
- virtualizarr/readers/fits.py
- virtualizarr/readers/hdf/__init__.py
- virtualizarr/readers/hdf/hdf.py
- virtualizarr/readers/hdf5.py
- virtualizarr/readers/kerchunk.py
- virtualizarr/readers/netcdf3.py
- virtualizarr/readers/tiff.py
- virtualizarr/tests/__init__.py
- virtualizarr/tests/test_backend.py
- virtualizarr/tests/test_integration.py
- virtualizarr/tests/test_manifests/test_array.py
- virtualizarr/tests/test_readers/test_dmrpp.py
- virtualizarr/tests/test_readers/test_hdf/test_hdf.py
- virtualizarr/tests/test_readers/test_kerchunk.py
- virtualizarr/tests/test_xarray.py
- virtualizarr/translators/kerchunk.py
- virtualizarr/writers/kerchunk.py
> Additions to `open_virtual_mfdataset`

- docs/api.rst
- docs/releases.rst
- pyproject.toml
- virtualizarr/backend.py
- virtualizarr/manifests/store.py
- virtualizarr/parallel.py
- virtualizarr/tests/__init__.py
- virtualizarr/tests/test_backend.py
> Final fixes for open_virtual_mfdataset

- virtualizarr/manifests/__init__.py
- virtualizarr/manifests/group.py
- virtualizarr/manifests/store.py
- virtualizarr/tests/test_manifests/test_group.py
- virtualizarr/tests/test_manifests/test_store.py
This also sets us up to add nested groups to the `ManifestStore`. @maxrjones I'm planning to merge this quickly FYI.
> Refactor ManifestGroup

- virtualizarr/readers/hdf/filters.py
> Apply typing simplification changes from #512 to hdf filters.

- docs/api.rst
- docs/releases.rst
- virtualizarr/__init__.py
- virtualizarr/accessor.py
- virtualizarr/tests/test_integration.py
- virtualizarr/writers/icechunk.py
> Support writing xarray.DataTree to Icechunk store

- pyproject.toml
Noticed this was just my old cworthy email, so I just added one person from each main org involved (FYI @maxrjones @norlandrhagen )
> Update contact emails

- pyproject.toml
Fixing lack of uploads at https://app.codecov.io/gh/zarr-developers/VirtualiZarr/pulls
> Fix coverage upload to codecov

- virtualizarr/manifests/store.py
- virtualizarr/tests/test_manifests/test_store.py
> Raise informative error if region detection fails

- conftest.py
- virtualizarr/tests/test_xarray.py
Double-checking that 2-dimension combining does actually work...
> Test 2d combine

- virtualizarr/tests/test_readers/test_hdf/test_hdf_filters.py
Accounts for new result after https://github.com/zarr-developers/numcodecs/pull/708
> Fix failing upstream test from numcodecs changes

- virtualizarr/translators/kerchunk.py
This fixes the failing mypy check
> Update type-ignore coverage

- .github/workflows/main.yml
- docs/api.md
- docs/data_structures.md
- mkdocs.yml
- pyproject.toml
Fix links to manifest objects, check docs builds, and add more inventories for cross-references.
> Fix and check links

- virtualizarr/tests/test_parsers/test_hdf/test_hdf_integration.py
- virtualizarr/xarray.py
> Add docstring for open_virtual_dataset and remove unused argument

- docs/index.md
- pyproject.toml
> Update example on homepage

- docs/index.md
- docs/usage.md
- pyproject.toml
Closes: https://github.com/zarr-developers/VirtualiZarr/issues/690
To Do:
> Updating usage doc to v2

- docs/migration_guide.md
- mkdocs.yml
> Update migration guide

- docs/releases.md
> Polish release notes

- .github/workflows/release.yml
- pyproject.toml
This should eliminate warnings and errors on the release workflow
> Update project metadata and bump release action

- docs/contributing.md
So I can be even lazier in future
> Add template for empty release notes in release guide

- docs/releases.md
- virtualizarr/codecs.py
- virtualizarr/tests/test_codecs.py
> Raise instead of silently dropping non-zarr custom codec

- docs/releases.md
Addresses https://github.com/zarr-developers/VirtualiZarr/pull/774#issuecomment-3188430234
@maxrjones
> Note breaking change of enforcing virtual chunk containers are correct
